service: monorepo
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, "us-east-1"}
  stage: ${opt:stage, "dev"}
  timeout: 30
  apiName: ${self:service}

plugins:
  - serverless-offline
  - serverless-deployment-bucket
  - serverless-prune-plugin
  - serverless-plugin-monorepo
  - serverless-dotenv-plugin

package:
  individually: true

custom:
  serverless-offline:
    httpPort: ${env:PORT, 3000}
    noPrependStageInUrl: true
  dotenv:
    path: .env
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION_NAME
      - AWS_SESSION_TOKEN
  prune:
    automatic: true
    number: 3

functions:
  search:
    handler: dist/src/index.search
    events:
      - http:
          path: /people
          method: get
          cors: true

  getSwapiAll:
    handler: dist/src/index.getSwapiAll
    events:
      - http:
          path: /people/swapi
          method: get
          cors: true

  create:
    handler: dist/src/index.create
    events:
      - http:
          path: /people
          method: post
          cors: true
